<?php

/**
 * Class WireMailMailgun
 *
 * @property string apiKey The API key set in config
 * @property string domain The domain for the API key
 */
class WireMailMailgun extends WireMail implements Module, ConfigurableModule
{
	private $apiUrl = 'https://api.mailgun.net/v3/';

	public static function getModuleInfo()
	{
		return array(
			'title' => 'Wire Mail Mailgun',
			'version' => '0.0.1',
			'summary' => "Extends WireMail through the Mailgun API",
			'href' => 'http://mailgun.com/',
			'author' => 'plauclair',
			'singular' => false,
			'autoload' => false
		);
	}

	/**
	 *
	 */
	public function ___send()
	{
		var_dump($this->mail);
		$request = curl_init();

		$postFields = [
			'from' => $this->getFrom(),
			'to' => $this->getToRecipients(),
			'subject' => $this->mail['subject'],
			'o:testmode' => $this->isTestMode(),
		];

		if ($this->getCCRecipients() !== false) {
			$postFields['cc'] = $this->getCCRecipients();
		}

		if ($this->getBCCRecipients() !== false) {
			$postFields['bcc'] = $this->getBCCRecipients();
		}

		if (!empty($this->mail['bodyHTML'])) {
			$postFields['html'] = $this->mail['bodyHTML'];
			// TODO: Replace the next line with something that
			// will output better plain text (break to newline especially)
			$postFields['text'] = (!empty($this->mail['body'])) ? $this->mail['body'] : strip_tags($this->mail['bodyHTML']);
		} else {
			$postFields['text'] = $this->mail['body'];
		}

		$options = array(
			CURLOPT_USERPWD => "api:{$this->apiKey}",
			CURLOPT_URL => "{$this->apiUrl}{$this->domain}/messages",
			CURLOPT_HEADER => false,
			CURLOPT_POST => true,
			CURLOPT_RETURNTRANSFER => true,
			CURLOPT_POSTFIELDS => $postFields,
			CURLOPT_HTTPHEADER => ['X-Mailer' => $this->mail['header']['X-Mailer']],
			CURLOPT_SSL_VERIFYPEER => $this->sslCheck(),
		);

		curl_setopt_array($request, $options);

		$response = curl_exec($request);

		if ($response === false) {
			// If an error occurred in cURL
			$this->log()->save('mailgun', 'cURL Error: ' . curl_error($request));
			curl_close($request);
			return 0;
		} else {
			$response = json_decode($response);

			$info = curl_getinfo($request);

			curl_close($request);

			switch ($info['http_code']) {
				case 200:
					return true; // Can't set int for number sent, since Mailgun doesn't return that data
					break;
				case 400:
					$this->log()->save('mailgun', "Code 400: Bad Request - {$response->message}.");
					return 0;
					break;
				case 401:
					$usedKey = (!empty($this->apiKey)) ? "API Key: {$this->apiKey}." : 'NO KEY SET.';
					$this->log()->save('mailgun', "Code 401: Unauthorized - No valid API key provided. {$usedKey}");
					return 0;
					break;
				case 402:
					// TODO: Improve this later
					$this->log()->save('mailgun', "Code 402: Request Failed - Parameters were valid but request failed.");
					return 0;
					break;
				case 404:
					$this->log()->save('mailgun', "Code 404: Not Found - The requested item doesn’t exist.");
					return 0;
					break;
				case 500:
					$this->log()->save('mailgun', "Code 500: Mailgun Server Error.");
					return 0;
					break;
				case 502:
					$this->log()->save('mailgun', "Code 502: Mailgun Server Error.");
					return 0;
					break;
				case 503:
					$this->log()->save('mailgun', "Code 503: Mailgun Server Error.");
					return 0;
					break;
				case 504:
					$this->log()->save('mailgun', "Code 504: Mailgun Server Error.");
					return 0;
					break;
			}
		}
	}


	/**
	 * Handles send() when new WireMail() is used instead
	 * of calling wireMail() directly
	 */
	public function send()
	{
		$this->___send();
	}

	/**
	 * Overrides the Mailgun API Key setting in config
	 *
	 * @param string $apiKey
	 */
	public function setApiKey($apiKey)
	{
		$this->apiKey = $apiKey;
	}

	/**
	 * Overrides the Domain Name setting in config
	 *
	 * @param string $domainName
	 */
	public function setDomainName($domainName)
	{
		$this->domain = $domainName;
	}

	/**
	 * Overrides the Test Mode setting in config
	 *
	 * @param bool $bool
	 */
	public function setTestMode($bool)
	{
		if (is_bool($bool)) {
			$this->testMode = ($bool === true) ? 'testMode' : false;
		}
	}

	/**
	 * Returns if the current instance is used in Test Mode
	 *
	 * @return bool
	 */
	private function isTestMode()
	{
		return ($this->testMode == 'testMode') ? true : false;
	}

	/**
	 * Returns if the current instance disables SSH check
	 *
	 * This can sometimes be needed on some testing environments,
	 * preferably don't use in production
	 *
	 * @return bool
	 */
	private function sslCheck()
	{
		return ($this->disableSslCheck == 'disableSslCheck') ? false : true;
	}


	/**
	 * Get the recipients of the To field in the proper format
	 *
	 * @return string|false
	 */
	private function getToRecipients()
	{
		$recipients = $this->mail['toName'];
		$to = [];

		foreach ($recipients as $email => $name) {
			$to[] = (empty($name)) ? $email : "{$name} <{$email}>";
		}

		return (!empty($to)) ? implode(',', $to) : false;
	}

	/**
	 * Set the email CC address
	 *
	 * Each added email addresses appends to any addresses already supplied, unless
	 * you specify NULL as the email address, in which case it clears them all.
	 *
	 * @param string|array|null $email Specify any ONE of the following:
	 *    1. Single email address or "User Name <user@example.com>" string.
	 *    2. CSV string of #1.
	 *    3. Non-associative array of #1.
	 *    4. Associative array of (email => name)
	 *    5. NULL (default value, to clear out any previously set values)
	 * @param string $name Optionally provide a FROM name, applicable
	 *    only when specifying #1 (single email) for the first argument.
	 * @return WireMail this
	 * @throws WireException if any provided emails were invalid
	 *
	 */
	public function cc($email = null, $name = null)
	{
		if (is_null($email)) {
			// clear existing values
			$this->mail['cc'] = array();
			$this->mail['ccName'] = array();
			return $this;
		}

		$emails = is_array($email) ? $email : explode(',', $email);

		foreach ($emails as $key => $value) {

			$ccName = '';
			if (is_string($key)) {
				// associative array
				// email provided as $key, and $ccName as value 
				$ccEmail = $key;
				$ccName = $value;

			} else if (strpos($value, '<') !== false && strpos($value, '>') !== false) {
				// ccName supplied as: "User Name <user@example.com"
				list($ccEmail, $ccName) = $this->extractEmailAndName($value);

			} else {
				// just an email address, possibly with name as a function arg
				$ccEmail = $value;
			}

			if (empty($ccName)) $ccName = $name; // use function arg if not overwritten
			$ccEmail = $this->sanitizeEmail($ccEmail);
			$this->mail['cc'][$ccEmail] = $ccEmail;
			$this->mail['ccName'][$ccEmail] = $this->sanitizeHeader($ccName);
		}

		return $this;
	}

	/**
	 * Get the recipients of the CC field in the proper format
	 *
	 * @return string|false
	 */
	private function getCCRecipients()
	{
		if (!empty($this->mail['ccName'])) {
			$recipients = $this->mail['ccName'];
			$cc = [];

			foreach ($recipients as $email => $name) {
				$cc[] = (empty($name)) ? $email : "{$name} <{$email}>";
			}

			return (!empty($cc)) ? implode(', ', $cc) : false;
		} else {
			return false;
		}
	}

	/**
	 * Set the email BCC address
	 *
	 * Each added email addresses appends to any addresses already supplied, unless
	 * you specify NULL as the email address, in which case it clears them all.
	 *
	 * @param string|array|null $email Specify any ONE of the following:
	 *    1. Single email address or "User Name <user@example.com>" string.
	 *    2. CSV string of #1.
	 *    3. Non-associative array of #1.
	 *    4. Associative array of (email => name)
	 *    5. NULL (default value, to clear out any previously set values)
	 * @param string $name Optionally provide a FROM name, applicable
	 *    only when specifying #1 (single email) for the first argument.
	 * @return WireMail this
	 * @throws WireException if any provided emails were invalid
	 *
	 */
	public function bcc($email = null, $name = null)
	{
		if (is_null($email)) {
			// clear existing values
			$this->mail['bcc'] = array();
			$this->mail['bccName'] = array();
			return $this;
		}

		$emails = is_array($email) ? $email : explode(',', $email);

		foreach ($emails as $key => $value) {

			$bccName = '';
			if (is_string($key)) {
				// associative array
				// email provided as $key, and $bccName as value 
				$bccEmail = $key;
				$bccName = $value;

			} else if (strpos($value, '<') !== false && strpos($value, '>') !== false) {
				// bccName supplied as: "User Name <user@example.com"
				list($bccEmail, $bccName) = $this->extractEmailAndName($value);

			} else {
				// just an email address, possibly with name as a function arg
				$bccEmail = $value;
			}

			if (empty($bccName)) $bccName = $name; // use function arg if not overwritten
			$bccEmail = $this->sanitizeEmail($bccEmail);
			$this->mail['bcc'][$bccEmail] = $bccEmail;
			$this->mail['bccName'][$bccEmail] = $this->sanitizeHeader($bccName);
		}

		return $this;
	}

	/**
	 * Get the recipients of the BCC field in the proper format
	 *
	 * @return string|false
	 */
	private function getBCCRecipients()
	{
		if (!empty($this->mail['bccName'])) {
			$recipients = $this->mail['bccName'];
			$bcc = [];

			foreach ($recipients as $email => $name) {
				$bcc[] = (empty($name)) ? $email : "{$name} <{$email}>";
			}

			return (!empty($bcc)) ? implode(', ', $bcc) : false;
		} else {
			return false;
		}
	}

	/**
	 * Get the From field in the proper format
	 *
	 * Will use WireMail()->from() if set first,
	 * module settings second and
	 * revert to default if nothing else is set
	 *
	 * @return string|false
	 */
	private function getFrom()
	{
		if (!empty($this->mail['from'])) {
			// Set manually
			return (empty($this->mail['fromName'])) ? $this->mail['from'] : "{$this->mail['fromName']} <{$this->mail['from']}>";
		} else if (!empty($this->fromEmail)) {
			// Set in settings
			return (empty($this->fromName)) ? "ProcessWire <{$this->fromEmail}>" : "{$this->fromName} <{$this->fromEmail}>";
		} else {
			// Default
			return "ProcessWire <processwire@{$this->domain}>";
		}
	}
}